# Generated by Django 3.2.6 on 2021-09-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'confirmed'), ('canceled', 'canceled')], default='pending', max_length=12),
        ),
    ]
